version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "19006:19006"
    depends_on:
      - backend
